export const itemToCategory = {
  'Shirt': 'Shirts',
  'T Shirt': 'Shirts',
  'Under T Shirt': 'Shirts',
  'Top': 'Tops',
  'Blouse': 'Tops',
  'Sweater': 'Tops',
  'Trouser': 'Bottoms',
  'Pajama': 'Bottoms',
  'Half Pant': 'Bottoms',
  'Skirt': 'Bottoms',
  'Lungi': 'Bottoms',
  'Suit': 'Suits',
  'Army Suit': 'Suits',
  'Pakistani Men Suit': 'Suits',
  'Pakistani Ladies Suit': 'Suits',
  'Coverall': 'Suits',
  'Baby Dress': 'Dresses',
  'Ladies Dress': 'Dresses',
  'Ladies Dress Big': 'Dresses',
  'Sari': 'Dresses',
  'Summer Kandoora': 'Traditional Items',
  'Hot Kandoora': 'Traditional Items',
  'Tarbooj': 'Traditional Items',
  'Ghutra': 'Traditional Items',
  'Hot Ghutra': 'Traditional Items',
  'Shimagh': 'Traditional Items',
  'Ghafia': 'Traditional Items',
  'Abaya': 'Traditional Items',
  'Shella': 'Traditional Items',
  'Jacket': 'Outerwear',
  'Under Wear': 'Accessories',
  'Socks': 'Accessories',
  'Tie': 'Accessories',
  'Cap': 'Accessories',
  'Bed Sheet Big': 'Bed Sheets',
  'Bed Sheet Small': 'Bed Sheets',
  'Bed Spread': 'Bed Sheets',
  'Bed Spread Big': 'Bed Sheets',
  'Blanket': 'Duvet Covers',
  'Blanket Big': 'Duvet Covers',
  'Pillow Cover': 'Pillow Cases & Cushion Covers',
  'Pillow': 'Pillow Cases & Cushion Covers',
  'Towel': 'Bathroom Items',
  'Towel Small': 'Bathroom Items',
  'Bath Towel': 'Bathroom Items',
  'Curtains': 'Carpets & Curtains',
  'Curtain Rubber': 'Carpets & Curtains',
  'Carpet': 'Carpets & Curtains',
  'Shoe': 'Shoes',
};

export const categoryGroups = {
  'Wash & Fold': [],
  'Clean & Iron': [
    'Shirts',
    'Tops',
    'Bottoms',
    'Suits',
    'Dresses',
    'Traditional Items',
    'Outerwear',
    'Accessories',
    'Bed Sheets',
    'Duvet Covers',
    'Pillow Cases & Cushion Covers',
    'Bathroom Items',
    'Carpets & Curtains',
    'Shoes',
  ],
  'Ironing': [
    'Shirts',
    'Tops',
    'Bottoms',
    'Suits',
    'Dresses',
    'Traditional Items',
    'Outerwear',
    'Accessories',
    'Bed Sheets',
    'Pillow Cases & Cushion Covers',
  ],
  'Duvets & Bulky': [
    'Blankets & Bedspreads',
    'Pillows',
    'Curtains',
    'Carpets',
  ],
  'Dry Cleaning': [
    'Shirts',
    'Tops',
    'Bottoms',
    'Suits',
    'Dresses',
    'Traditional Items',
    'Outerwear',
    'Accessories',
    'Bed Sheets',
    'Duvet Covers',
    'Pillow Cases & Cushion Covers',
    'Bathroom Items',
    'Carpets & Curtains',
    'Shoes',
  ],
};

export const categoryToItems = {
  'Blankets & Bedspreads': ['Blanket', 'Blanket Big', 'Bed Spread', 'Bed Spread Big'],
  'Pillows': ['Pillow', 'Pillow Cover'],
  'Curtains': ['Curtains', 'Curtain Rubber'],
  'Carpets': ['Carpet'],
};